title: Ephron M # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I'm a blended package of a Data Scientist, ML Engineer, and MLOPS developer with more than 2 years of experience who could help you solve your business problems by providing scalable LLM-based solutions tailored to your specific use case.
  <br><br>
  -  Analyze internal dataset to find feature relationships
  -  Suggest best LLM or ML solution for your use case
  -  Budget cloud-based development for scalability
  -  Focus on CI/CD pipelines for future AI retraining using MLOps
  -  Work as solo contributor or in team setting
  -  Prioritize workload based on project schedule
  <br><br>
  <a href="https://www.linkedin.com/in/ephron-martin/">LinkedIn </a> <br>
  <a href="https://github.com/EphronM">Github Profile</a> <br>
  <a href="https://medium.com/@ephronM">Medium Profile</a> <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E8GY0QF353 # your Google Analytics tracking ID here
