title: Ephron M # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I'm a blended package of a Data Scientist, ML Engineer, and MLOPS developer with more than 2 years of experience who could help you solve your business problems by providing scalable LLM-based solutions tailored to your specific use case.
  <br><br>
  <ul>
    <li>Analyze internal dataset to find feature relationships</li>
    <li>Suggest best LLM or ML solution for your use case</li>
    <li>Budget cloud-based development for scalability</li>
    <li>Focus on CI/CD pipelines for future AI retraining using MLOps</li>
    <li>Work as solo contributor or in team setting</li>
    <li>Prioritize workload based on project schedule</li>
  </ul>
  <br><br>
  <a href="https://www.linkedin.com/in/ephron-martin/">LinkedIn</a> 
  <a href="https://github.com/EphronM">Github</a> 
  <a href="https://medium.com/@ephronM">Medium</a> <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E8GY0QF353 # your Google Analytics tracking ID here
