title: Ephron M # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  ####I'm a blended package of a Data Scientist, ML Engineer, and MLOPS developer with more than 2 years of experience who could help you solve your business problems by providing scalable LLM-based solutions tailored to your specific use case.
  <br><br>
  - Analysis of your Internal dataset to find the relationship between features<br>
  - Suggest the best LLM or ML solution that could solve your use case.<br>
  - Budgeting the development solutions as cloud-based for better scalability.<br>
  - Focuses on CI-CD pipelines for future retraining of the AI-based solution using MLOPS<br>
  - Can work as a solo contributor and also in a team setting. Will prioritise the workload based on the project schedule.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/ephron-martin/">LinkedIn Profile</a> <br>
  <a href="https://github.com/EphronM">Github Profile</a> <br>
  <a href="https://medium.com/@ephronM">Medium Profile</a> <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E8GY0QF353 # your Google Analytics tracking ID here
